# Generated by Django 4.2.2 on 2023-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True, default='https://i.imgur.com/eeImLXD.png', null=True),
        ),
    ]
